### ISSUE TITLE
missed launch script "spring-integration-netty4"?

### ISSUE THREAD

**Issue by vincentruan** [jetoile/spring-integration-netty4#1]
hi, would you like to provide this script?

**Comment by jetoile** [comment]
Hello, 

Do you mean that you want a script to run the main class?
If so, you can find a tar.gz which is generated in package phase which allow you to run the program.

**Comment by vincentruan** [comment]
yes, I want a script to run the main class. And where is the tar.gz? There is no release, and I used maven command to build but still no.

**Comment by jetoile** [comment]
Maven generate a tar.gz into your target folder.
Once unzip, do a `./bin/spring-integration-netty4 console`

**Comment by vincentruan** [comment]
Yeah,  maybe the problem came because of my the maven assembly plugin. I generated this script file success after reinstall maven. Thanks jetoile. :-D
